In [1]:
## 모듈 로딩
import numpy as np


In [2]:
## ndarray 타입 데이터 생성

# 0으로 채워진 ndarray 객체 생성 ==> zeros()
np.zeros(2)


array([0., 0.])

In [3]:
np.zeros((2, 3), dtype=np.int8)


array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [9]:
# 1로 채워진 ndarray 객체 생성 ==> ones()
np.ones(10), np.ones(10, dtype=np.int32), np.ones((2, 5), dtype=np.bool_)


(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]))

In [10]:
# 랜덤 데이터로 ndarray 객체 생성 ==> random
np.random.randint(1, 5, (3, 10))


array([[4, 4, 3, 3, 1, 2, 3, 4, 4, 3],
       [3, 4, 1, 3, 1, 3, 4, 2, 1, 1],
       [4, 1, 4, 3, 4, 1, 4, 1, 4, 4]])

In [16]:
# 0 <= 범위 < 1
np.random.rand(5, 2), np.random.rand(3)


(array([[0.77234733, 0.16231951],
        [0.9215816 , 0.03601476],
        [0.02202768, 0.01882965],
        [0.09720523, 0.80655219],
        [0.81280513, 0.34354338]]),
 array([0.82895719, 0.01358993, 0.76484576]))

In [19]:
np.random.randn(5), np.random.randn(1, 2, 3)


(array([ 0.12594384, -0.32738094,  1.30792077, -0.95055733,  0.26373475]),
 array([[[-1.42770012,  0.38753056,  1.40289179],
         [-1.0078411 , -0.18539112, -0.2463388 ]]]))

In [26]:
# 랜덤 고정
np.random.seed(4)

np.random.randn(5)


array([ 0.05056171,  0.49995133, -0.99590893,  0.69359851, -0.41830152])

In [27]:
data = np.random.randn(10)
print(data)

np.random.shuffle(data)
print(data)


[-1.58457724 -0.64770677  0.59857517  0.33225003 -1.14747663  0.61866969
 -0.08798693  0.4250724   0.33225315 -1.15681626]
[-1.14747663  0.33225315 -1.58457724  0.61866969 -0.08798693 -0.64770677
 -1.15681626  0.4250724   0.33225003  0.59857517]


In [28]:
data.sum(), data.max(), data.min()


(-2.317743386975293, 0.6186696890268814, -1.5845772351121241)

In [31]:
data.argmax(), data.argmin()


(3, 2)