## [ 기본적인 이미지 다루기 ]


In [1]:
### ===> 모듈 로딩
import cv2
import numpy as np


-   [1] 이미지 데이터 로딩 <hr>
    -   컬러 / 회색 이미지 변환 로딩 가능함


In [2]:
file = "../data/img/cat05.jpg"


In [3]:
### => 컬러 이미지 로딩 [기본값]
img_rgb = cv2.imread(file, cv2.IMREAD_COLOR)

### => 회색 이미지 로딩 [기본값]
img_gray = cv2.imread(file, cv2.IMREAD_GRAYSCALE)


In [4]:
### 이미지 데이터 정보확인
print(f"[Color IMAGE]")
print(f"SHAPE : {img_rgb.shape}    DIM : {img_rgb.ndim}차원")
print(f"DTYPE : {img_rgb.dtype}    SIZE : {img_rgb.size}바이트")


[Color IMAGE]
SHAPE : (185, 273, 3)    DIM : 3차원
DTYPE : uint8    SIZE : 151515바이트


In [5]:
### 이미지 데이터 정보확인
print(f"[Gray IMAGE]")
print(f"SHAPE : {img_gray.shape}    DIM : {img_gray.ndim}차원")
print(f"DTYPE : {img_gray.dtype}    SIZE : {img_gray.size}바이트")


[Gray IMAGE]
SHAPE : (185, 273)    DIM : 2차원
DTYPE : uint8    SIZE : 50505바이트


In [6]:
if img_rgb is not None:
    ### => 이미지 창 띄우기
    cv2.imshow("[ COLOR ]", img_rgb)

    while True:
        ### => 이미지 창 제어
        key = cv2.waitKey()
        print(f"key =>> {key} - {hex(key)}")
        if key == 27:  # ESC
            cv2.destroyAllWindows()
            break
else:
    print("No image file!!!")


key =>> 13 - 0xd
key =>> 27 - 0x1b


In [7]:
save_filename = "../data/img/cat05_copy.jpg"
img_file = cv2.imwrite(save_filename, img_rgb)


In [8]:
img_file = "../data/img/cat02.jpg"
img_file2 = "../data/img/DysonSphere03.jpg"
img = cv2.imread(img_file, cv2.IMREAD_COLOR)
img2 = cv2.imread(img_file2, cv2.IMREAD_COLOR)


In [9]:
img_b, img_g, img_r = cv2.split(img)

cv2.imshow("[Blue Channel]", img_b)
cv2.waitKey(1000)
cv2.destroyWindow("[Blue Channel]")
cv2.imshow("[Green Channel]", img_g)
cv2.waitKey(1000)
cv2.destroyWindow("[Green Channel]")
cv2.imshow("[Red Channel]", img_r)
cv2.waitKey(1000)
cv2.destroyAllWindows()


In [10]:
b, g, r = img[:, :, 0], img[:, :, 1], img[:, :, 2]

cv2.imshow("[IMG-R]", r)
cv2.waitKey(1000)
cv2.destroyAllWindows()
cv2.imshow("[IMG-G]", g)
cv2.waitKey(1000)
cv2.destroyAllWindows()
cv2.imshow("[IMG-B]", b)
cv2.waitKey(1000)
cv2.destroyAllWindows()


In [11]:
img_b, img_g, img_r = cv2.split(img2)

img_rgb = cv2.merge((img_r, img_g, img_b))

cv2.imshow("[RGB IMAGE]", img_rgb)

cv2.waitKey()
cv2.destroyAllWindows()


In [12]:
src_hsv = cv2.cvtColor(img2, cv2.COLOR_BGR2HSV)
planes = cv2.split(src_hsv)

cv2.imshow("[HSV IMG]", src_hsv)

cv2.waitKey()
cv2.destroyAllWindows()


In [13]:
down_img = cv2.resize(img, dsize=(180, 150), interpolation=cv2.INTER_AREA)
up_img = cv2.resize(img2, dsize=(0, 0), fx=1.2, fy=1.2, interpolation=cv2.INTER_CUBIC)

cv2.imshow("down_img", down_img)
cv2.imshow("up_img", up_img)

if (
    cv2.waitKey()
    or cv2.getWindowProperty("up_img", cv2.WND_PROP_VISIBLE) < 1
    or cv2.getWindowProperty("down_img", cv2.WND_PROP_VISIBLE) < 1
):
    cv2.destroyAllWindows()


In [36]:
### 도화지 만들기
img = np.zeros((300, 300), dtype=np.uint8)
img = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
img_w = np.full((300, 300), 255, dtype=np.uint8)
img_w = cv2.cvtColor(img_w, cv2.COLOR_GRAY2BGR)
img.shape, img.ndim


((300, 300, 3), 3)

In [38]:
### 이미지 데이터에 그림 그리기
cv2.line(img, (0, 0), (70, 70), (255, 255, 0))
cv2.line(img, (20, 100), (250, 20), (255, 255, 255), 20, cv2.LINE_AA)

print(img.shape)


(300, 300, 3)


In [40]:
cv2.imshow("BLACK", img)
cv2.imshow("WHITE", img_w)
cv2.waitKey(5000)
cv2.destroyAllWindows()


In [41]:
img = np.full((500, 500, 3), 255, dtype=np.uint8)
cv2.imwrite("../data/img/blank_500.jpg", img)


True

In [59]:
img = cv2.imread("../data/img/blank_500.jpg")

cv2.line(img, (50, 50), (150, 50), (255, 0, 0))
cv2.line(img, (200, 50), (300, 50), (0, 255, 0))
cv2.line(img, (350, 50), (450, 50), (0, 0, 255))

cv2.line(img, (100, 100), (400, 100), (255, 255, 0), 10)
cv2.line(img, (100, 150), (400, 150), (255, 0, 255), 10)
cv2.line(img, (100, 200), (400, 200), (0, 255, 255), 10)
cv2.line(img, (100, 250), (400, 250), (200, 200, 200), 10)
cv2.line(img, (100, 300), (400, 300), (0, 0, 0), 10)

cv2.line(img, (100, 350), (400, 400), (0, 0, 255), 20, cv2.LINE_4)
cv2.line(img, (100, 400), (400, 450), (0, 0, 255), 20, cv2.LINE_8)
cv2.line(img, (100, 450), (400, 500), (0, 0, 255), 20, cv2.LINE_AA)
cv2.line(img, (0, 0), (500, 500), (0, 0, 255))

cv2.imshow("lines", img)
cv2.waitKey(10000)
cv2.destroyAllWindows()


In [60]:
img = cv2.imread("../data/img/blank_500.jpg")

cv2.rectangle(img, (50, 50), (150, 150), (255, 0, 0))
cv2.rectangle(img, (300, 300), (100, 100), (0, 255, 0), 10)
cv2.rectangle(img, (450, 200), (200, 450), (0, 0, 255), -1)

cv2.imshow("rectangle", img)
cv2.waitKey(10000)
cv2.destroyAllWindows()


In [61]:
img = cv2.imread("../data/img/blank_500.jpg")

pts1 = np.array([[50, 50], [150, 150], [100, 140], [200, 240]], dtype=np.int32)
pts2 = np.array([[350, 50], [250, 200], [450, 200]], dtype=np.int32)
pts3 = np.array([[150, 300], [50, 450], [250, 450]], dtype=np.int32)
pts4 = np.array(
    [[350, 250], [450, 350], [400, 450], [300, 450], [250, 350]], dtype=np.int32
)

cv2.polylines(img, [pts1], False, (255, 0, 0))
cv2.polylines(img, [pts2], False, (0, 0, 0), 10)
cv2.polylines(img, [pts3], True, (0, 0, 255), 10)
cv2.polylines(img, [pts4], True, (0, 0, 0))

cv2.imshow("polyline", img)
cv2.waitKey(10000)
cv2.destroyAllWindows()


In [58]:
img = cv2.imread("../data/img/blank_500.jpg")

cv2.circle(img, (150, 150), 100, (255, 0, 0))
cv2.circle(img, (300, 150), 70, (0, 255, 0), 5)
cv2.circle(img, (400, 150), 50, (0, 0, 255), -1)

cv2.ellipse(img, (50, 300), (50, 50), 0, 0, 360, (0, 0, 255))
cv2.ellipse(img, (150, 300), (50, 50), 0, 0, 180, (255, 0, 0))
cv2.ellipse(img, (200, 300), (50, 50), 0, 181, 360, (0, 0, 255))

cv2.ellipse(img, (325, 300), (75, 50), 0, 0, 360, (0, 255, 0))
cv2.ellipse(img, (450, 300), (50, 75), 0, 0, 360, (255, 0, 255))

cv2.ellipse(img, (50, 425), (50, 75), 15, 0, 360, (0, 0, 0))
cv2.ellipse(img, (200, 425), (50, 75), 45, 0, 360, (0, 0, 0))

cv2.ellipse(img, (350, 425), (50, 75), 45, 0, 180, (0, 0, 255))
cv2.ellipse(img, (400, 425), (50, 75), 45, 181, 360, (255, 0, 0))

cv2.imshow("circle", img)
cv2.waitKey(10000)
cv2.destroyAllWindows()


In [65]:
img = cv2.imread("../data/img/blank_500.jpg")

cv2.putText(img, "Plain", (50, 30), cv2.FONT_HERSHEY_PLAIN, 1, (0, 0, 0))
cv2.putText(img, "Simplex", (50, 70), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 0))
cv2.putText(img, "Duplex", (50, 110), cv2.FONT_HERSHEY_DUPLEX, 1, (0, 0, 0))
cv2.putText(img, "Simplex", (200, 110), cv2.FONT_HERSHEY_SIMPLEX, 2, (0, 0, 250))

cv2.putText(
    img, "Complex Small", (50, 180), cv2.FONT_HERSHEY_COMPLEX_SMALL, 1, (0, 0, 0)
)
cv2.putText(img, "Complex", (50, 220), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 0, 0))
cv2.putText(img, "Triplex", (50, 260), cv2.FONT_HERSHEY_TRIPLEX, 1, (0, 0, 0))
cv2.putText(img, "Complex", (200, 260), cv2.FONT_HERSHEY_TRIPLEX, 2, (0, 0, 255))

cv2.putText(
    img, "Script Simplex", (50, 330), cv2.FONT_HERSHEY_SCRIPT_SIMPLEX, 1, (0, 0, 0)
)
cv2.putText(
    img, "Script Complex", (50, 370), cv2.FONT_HERSHEY_SCRIPT_COMPLEX, 1, (0, 0, 0)
)

cv2.putText(
    img,
    "Plain Italic",
    (50, 430),
    cv2.FONT_HERSHEY_PLAIN | cv2.FONT_ITALIC,
    1,
    (0, 0, 0),
)
cv2.putText(
    img,
    "Complex Italic",
    (50, 470),
    cv2.FONT_HERSHEY_COMPLEX | cv2.FONT_ITALIC,
    1,
    (0, 0, 0),
)

cv2.imshow("draw text", img)
cv2.waitKey(10000)
cv2.destroyAllWindows()


In [78]:
img_w3d5 = np.full(((256, 400, 3)), 255, dtype=np.uint8)
cv2.rectangle(img_w3d5, (0, 0), (399, 255), (0, 0, 255), thickness=-1)
cv2.circle(img_w3d5, (150, 100), 32, (255, 255, 255), thickness=-1)
cv2.circle(img_w3d5, (250, 100), 32, (255, 255, 255), thickness=-1)
cv2.circle(img_w3d5, (200, 180), 16, color=(255, 255, 255), thickness=2)
cv2.circle(img_w3d5, (200, 120), 100, (255, 255, 255), thickness=2)

for i in range(100):
    cv2.imshow(str(i), img_w3d5)
    cv2.moveWindow(str(i), np.random.randint(0, 1919), np.random.randint(0, 1079))
cv2.waitKey()
cv2.destroyAllWindows()


In [79]:
img_w3d5 = cv2.imread("../data/img/KakaoTalk_20240320_172649524.png")

for i in range(100):
    cv2.imshow(str(i), img_w3d5)
    cv2.moveWindow(str(i), np.random.randint(0, 1919), np.random.randint(0, 1079))
cv2.waitKey()
cv2.destroyAllWindows()


In [90]:
frontalface_model = "../data/haarcascades/haarcascade_frontalface_alt2.xml"
img_file = "../data/img/KakaoTalk_20240314_220343459.jpg"

face_detector = cv2.CascadeClassifier(frontalface_model)

imgNP = cv2.imread(img_file)

face_detections = face_detector.detectMultiScale(imgNP, scaleFactor=1.1)
print(f"** face_detections RESULT\n{face_detections}")

for x, y, w, h in face_detections:
    cv2.rectangle(imgNP, (x, y), (x + w, y + h), (0, 255, 0), 2)

cv2.imshow("[M]", imgNP)

if cv2.waitKey() or cv2.getWindowProperty("image", cv2.WND_PROP_VISIBLE) < 1:
    cv2.destroyAllWindows()


** face_detections RESULT
[[495 510  84  84]
 [726 602  82  82]
 [682 600  61  61]]


In [91]:
frontalface_model = "../data/haarcascades/haarcascade_eye.xml"
face_detector = cv2.CascadeClassifier(frontalface_model)

## 카메라 연결
camera = cv2.VideoCapture(0)

if not camera.isOpened():
    while True:
        camImg = cv2.imread(camera)
        face_detector = cv2.CascadeClassifier(camera)

        if len(face_detections):
            for x, y, w, h in face_detections:
                cv2.rectangle(camera, (x, y), (x + w, y + h), (0, 255, 0), 2)
            cv2.imshow("[M]", camera)

            if (
                cv2.waitKey()
                or cv2.getWindowProperty("image", cv2.WND_PROP_VISIBLE) < 1
            ):
                camera.release()
                cv2.destroyAllWindows()
